### ISSUE TITLE
Fixed some typos in Portuguese and Spanish Json Files

### ISSUE THREAD

**Issue by jvxis** [g45t345rt/g45w#1]
Hi,
I attached both files by replacing the .json extension to .txt

[es.txt](https://github.com/g45t345rt/g45w/files/12017585/es.txt)
[pt.txt](https://github.com/g45t345rt/g45w/files/12017587/pt.txt)

**Comment by g45t345rt** [comment]
Thx! Will update later and add your github handle in the readme contributors section :D
