### ISSUE TITLE
Donate button crashed on Windows

### ISSUE THREAD

**Issue by gedw99** [g45t345rt/g45w#10]
I wanted to use this from Windows.

Everything works but the donate button causes app to crash.

If you don't have windows I recommend using UTM for Mac: https://formulae.brew.sh/cask/utm

You can download a Windows 11 ISO using Crystal Fetch for Mac.

**Comment by gedw99** [comment]
The same function works on all other OS btw .

i imagine it’s to do with the gio-x packsge that opens a Hyperlink

**Comment by g45t345rt** [comment]
Yep, I was able to reproduce. I will fix later.
Thx for reporthing.

**Comment by gedw99** [comment]
> Yep, I was able to reproduce. I will fix later. Thx for reporthing.

thanks. If you dont have Windows, just ping me and I will compile and test here.

also there is a way to do this in CI too.

**Comment by g45t345rt** [comment]
Fixed in latest commit.

**Comment by gedw99** [comment]
Thanks @g45t345rt 

will test here on windows arm64

**Comment by gedw99** [comment]
Hey @g45t345rt 


macos-arm64 works, in that it does not crash,

<img width="612" alt="macos-arm64" src="https://github.com/g45t345rt/g45w/assets/53147028/7ce00105-c0cf-4818-8c0b-79fc956d4455">

windows-arm64 crashes when I click the donate button.
I compiled this on Mac btw. 

<img width="483" alt="windows-arm64" src="https://github.com/g45t345rt/g45w/assets/53147028/c40a7f01-515c-4e8a-8134-09092c69aa61">

**Comment by gedw99** [comment]
The Windows VM needs an OS update and now the error in the GIO app is different,

<img width="386" alt="Screenshot 2024-01-02 at 15 34 03" src="https://github.com/g45t345rt/g45w/assets/53147028/a7d33449-cfe9-45e2-8914-a410a522ba44">

**Comment by g45t345rt** [comment]
Yeah, if the node is not synced, the smart contract will not be available. As always, thanks for testing!
