### ISSUE TITLE
Transactions History - Like CLI wallet

### ISSUE THREAD

**Issue by jvxis** [g45t345rt/g45w#2]
Option to show the transaction history with the same info as we have on CLI Wallet.

**Comment by g45t345rt** [comment]
Agreed, but this feature will only be available if you are connected to a full node.

**Comment by g45t345rt** [comment]
Implemented and available in next release.

**Comment by jvxis** [comment]
> Implemented and available in next release.

Great mate. Thanks!

**Comment by jvxis** [comment]
Is it available to compile and test?

**Comment by g45t345rt** [comment]
Yep you can build from latest :)

**Comment by jvxis** [comment]
I built it, but it shows no transactions when I open a wallet.
