### ISSUE TITLE
Wallet Transaction History - Comments

### ISSUE THREAD

**Issue by jvxis** [g45t345rt/g45w#4]
Hi, is it possible to include a pop-up with the comments inside the transaction?

Thanks,
JVX

<img width="369" alt="Captura de Tela 2023-08-01 às 11 00 05" src="https://github.com/g45t345rt/g45w/assets/108929149/3a7d77fc-acb7-4426-b5c8-1d54b5144c89">

**Comment by g45t345rt** [comment]
In latest commit, clicking transaction will now reveal all info including comments if available.

**Comment by jvxis** [comment]
Amazing. Well done mate!
