### ISSUE TITLE
For mobile have back button on bottom

### ISSUE THREAD

**Issue by gedw99** [g45t345rt/g45w#6]
Would it be possible to put the back button on the bottom for mobile ?

makes it faster on tall mobile to hit the back button

**Comment by gedw99** [comment]
There is another way .

Gio does not have the swipe back option like all Apple apps.

i think it’s possible to implement it for all device targets via the gio gesture op.

Is just a matter of detecting a long horizontal swipe from right to left for navigating back.

on androids I would leave it turned on actually even though those users are used to having to use a back button

**Comment by g45t345rt** [comment]
Good idea! I will experiment with the gesture op and see what I can do.
As you mentioned, this could be really useful for both IOS and Android, even though Android already has the native back button.

**Comment by g45t345rt** [comment]
No bottom back button but swipe left implemented.
Thx for the idea!
